### ISSUE TITLE
[studio] Upgrading Studio and publishing can result in failed pubs

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1314] opened 2017-09-06 19:26 UTC
Steps to Reproduce
===============
* Build 3.0.0 by cloning `craftercms` version `3.0.0`:
```
git clone -bv3.0.0 http://github.com/craftercms/craftercms/ craftercms300
cd craftercms300
./gradlew -Pcrafter.git.branch=v3.0.0 init build deploy
./crafter-auth-env/bin/crafter.sh start
```
** Note we have to use `crafter.sh` to start this auth env
* Login to Studio and create an Editorial BP site
* Edit the hompage and make a change and publish it
* Edit the homepage and make another change but don't publish
* Shutdown Crafter
* Switch to Crafter 3.0.1 (don't start it yet)
* Copy the `data` folder from auth in 3.0.0 to overwrite the data folder in 3.0.1
* Start 3.0.0
* Go to the site you created
* Click on History of the homepage and revert to the change before last and see it work
* Click on History of the homepage and revert to the change before last (again) and see it go back
* Edit the homepage, make a change and save it
* Publish the homepage

The publisher fails with the errors: https://gist.github.com/sumerjabri/b46ad9f57f01338c28674dfda10e7fa7

**Comment by dejan-brkic** [comment] 2017-09-12 18:29
This is configuration issue. When `data` was copied over, published repo still points to "old" sandbox repo as remote origin. Configuration can be fixed manually and publishing will start working again. Issue is caused by using absolute paths when cloning sandbox into published repo. Fixed it by using relative paths instead.

PR:
https://github.com/craftercms/studio/pull/856

**Comment by sumerjabri** [comment] 2017-10-02 15:11
Still happening:
https://gist.github.com/sumerjabri/7e5c91eea554af27ac762c46cad1d6e8

**Comment by dejan-brkic** [comment] 2017-10-02 21:42
There is no code fix for this issue. Problem is how `published` repo is being created in 3.0.0 (absolute path). When data repo is moved around in upgrade process, `published` repo loses reference to `origin` (`sandbox`) because it has absolute path written in config file. (e.g.)
```
[remote "origin"]
	url = /my/absolute/path/to/sandbox/craftercms300/crafter-auth-env/bin/../data/repos/sites/test/sandbox
	fetch = +refs/heads/*:refs/remotes/origin/*
```
Only solution is to manually update configuration file to something like this:
```
[remote "origin"]
	url = ../sandbox
	fetch = +refs/heads/*:refs/remotes/origin/*
```

Another option (in the future) would be creating a UI or admin tool that could fix lost reference between `sandbox` and `published`.

Code fix that was provided before is to prevent this issue in future releases by using relative path as reference for `origin` in `published` configuration

**Comment by sumerjabri** [comment] 2017-10-03 13:07
@dejan-brkic please update documentation: http://docs.craftercms.org/en/3.0/system-administrators/studio/debugging-publishing-issues.html

This is another issue that can happen and what you described will help people fix it manually as you suggest.

**Comment by dejan-brkic** [comment] 2017-10-03 16:29
Documented
PR:
https://github.com/craftercms/docs/pull/365

**Closed** 2017-10-03 18:44 UTC
Labels: bug, Priority: High
