### ISSUE TITLE
Engine, in Preview mode must authenticate against studio and authorize inbound requests

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#344] opened 2017-01-10 18:31 UTC

**Comment by russdanner** [comment] 2017-03-02 17:21
Sumer, let's discuss.

**Comment by sumerjabri** [comment] 2017-03-21 18:12
Closing. When the issue is more fully defined, please create a full/clear ticket.

Or, let's discuss and create actionable tickets for the team if it makes more sense that way.

**Closed by sumerjabri** 2017-03-21 18:12 UTC
