### ISSUE TITLE
The `etag` filter is not handling encoding of non-Latin characters correctly

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6634] opened 2024-03-15 20:23 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

`UTF-8` characters are being "garbled" in delivery where the `E-Tag` filter is configured to be enabled. 
(The issue is NOT present in preview mode)

### Steps to reproduce

Steps:

1. Create a site based on empty blueprint
2. Edit the template and add the following to the template in a visible location `©`
3. Save the template and publish it to a delivery site
4. visit the site and see the issue

If you disable the `etag` filter (via `server-config.properties`), this issue will go away.

**Comment by phuongnq** [comment] 2024-03-22 06:15
@sumerjabri @russdanner I cannot reproduce this in the current state. Could be the new version of Spring 5.3.33 fixed the issue.

![2024-03-22_11-02](https://github.com/craftercms/craftercms/assets/2996543/cd8af115-359e-4963-940b-55e9b1e79dfd)

**Comment by sumerjabri** [comment] 2024-03-22 20:51
Please try again with the tag `v4.1.3` to see if that can be reproduced. If that's the case, then we know the latest Spring probably fixed it.

**Comment by sumerjabri** [comment] 2024-03-27 14:44
@avasquez614 was not able to reproduce this in 4.1.4 either. Closing as not reproducible.

**Closed by sumerjabri** 2024-03-27 14:44 UTC
Labels: bug, priority: high, CI, can't reproduce, module: engine
