### ISSUE TITLE
[studio-ui] Update to use Monitoring APIv2

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#2926] opened 2019-03-08 15:18 UTC
The `About` dialog need to be updated to use the new Monitoring API v2

https://app.swaggerhub.com/apis/craftercms/studio/2.0.20#/monitoring/getVersion
 
<img width="589" alt="screen shot 2019-03-08 at 9 15 49 am" src="https://user-images.githubusercontent.com/1236955/54037112-fe544400-4182-11e9-8bd8-a2700eb7f8e6.png">

**Comment by sumerjabri** [comment] 2019-03-08 15:26
Duplicate of: https://github.com/craftercms/craftercms/issues/2922

**Closed** 2019-03-08 15:27 UTC
Labels: duplicate
