### ISSUE TITLE
[Studio] Studio allows to delete the user currently connected.

### ISSUE THREAD

**Issue by gortizcraftersoftware** [craftercms/craftercms#784] opened 2017-05-04 20:32 UTC
Steps:
1. Create a user with the role admin.
2. Login with the user recently created.
3. Go to User tab
4. Delete the user currently connected.

Current behavior
Studio allows to delete the user currently connected.

Expected behavior
When the this user is deleted studio is crash, never should delete the user current connected.

**Comment by sumerjabri** [comment] 2017-05-04 21:47
Duplicate of https://github.com/craftercms/craftercms/issues/626

**Closed by sumerjabri** 2017-05-04 21:47 UTC
Labels: duplicate
