### ISSUE TITLE
[studio] SQL error when Bulk Publish executed on `/` path

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#3869] opened 2020-03-05 11:59 UTC
Probable cause is sending an empty list of paths to SQL query.

Stack trace observed in log files.

```
### The error may exist in org/craftercms/studio/api/v1/dal/ItemStateMapper.xml
### The error may involve org.craftercms.studio.api.v1.dal.ItemStateMapper.getMandatoryParentsForPublishing-Inline
### The error occurred while setting parameters
### SQL: SELECT is1.path as path         FROM item_state is1         WHERE is1.site = ?         AND is1.path IN                   AND is1.state IN          (               ?          ,              ?          ,              ?          ,              ?          ,              ?          ,              ?          ,              ?          ,              ?          ,              ?          ,              ?          ,              ?          )          UNION         SELECT is2.path as path         FROM (item_state is2 INNER JOIN item_metadata im2 ON is2.path = im2.path AND is2.site = im2.site)         WHERE is2.site = ?         AND im2.renamed > 0         AND is2.path IN                   AND is2.state IN          (               ?          ,              ?          ,              ?          ,              ?          ,              ?          ,              ?          ,              ?          ,              ?          ,              ?          ,              ?          ,              ?          )
### Cause: java.sql.SQLSyntaxErrorException: (conn:26) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND is1.state IN
         (
            'NEW_UNPUBLISHED_LOCKED'
         ,
 ' at line 6
```

**Comment by russdanner** [comment] 2020-03-13 15:20
@dejan-brkic What is a good generic test we can use to verify this?

**Comment by sumerjabri** [comment] 2020-03-19 22:52
@russdanner we think we got it, and haven't made things worse. We're unable to reproduce/test beyond this. I'm closing this ticket and we can reopen if the issue surfaces again.

**Closed by sumerjabri** 2020-03-19 22:52 UTC
Labels: CI, bug, priority: high
