### ISSUE TITLE
[Studio] Duplicate operation does not set the right LifecycleOperation for the ContentProcessorPipeline

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#330] opened 2016-12-29 17:04 UTC
We have a custom Processor that updates documents when they are copied or duplicated, it works fine using the "Copy & Paste" option but not when using "Duplicate".

The processor is validating these values:
- ContentLifeCycleOperation.COPY
- ContentLifeCycleOperation.DUPLICATE

But the DmConstants.CONTENT_LIFECYCLE_OPERATION key returns null.

**Comment by dejan-brkic** [comment] 2017-01-05 19:18
@russdanner 
Seems like UI issue. Duplicate service is not executed at all. Instead write content service is called (meaning it is creating new content with same content, instead of duplicating it)

**Comment by russdanner** [comment] 2017-01-11 21:09
I think the UI was used to implement because the backend was not duplicating children.  I will research.

**Comment by russdanner** [comment] 2017-01-11 21:26
@dejan-brkic: Confirmed in UI it's calling a bunch of writes.  We should move this back to the server.  I know we're busy so do you want me to open a ticket for C3 for this or fix server side call in C2?

If we go with UI/C2 implementation and move to server in C3:  Why in C2, with the UI doing the work via the WRITE rest API, isn't the lifecycle set to one of the following:

DmContentLifeCycleService.ContentLifeCycleOperation.NEW 
DmContentLifeCycleService.ContentLifeCycleOperation.UPDATE

**Comment by russdanner** [comment] 2017-01-11 21:27
UI that needs to be moved back to server is here:
https://github.com/craftercms/studio2-ui/blob/2.5.x/static-assets/components/cstudio-common/common-api.js

**Comment by russdanner** [comment] 2017-01-11 21:27
Assigned for feedback

**Comment by dejan-brkic** [comment] 2017-01-11 21:49
I think life cycle operation is set on backend depending on operation that is performed (writes vs clipboard). There is no default operation. Specially that doing writes in UI (or groovy), regular action flow might be bypassed so it does not set life cycle operation.
Regarding C2 vs C3, is up to you when we move that into backend.

**Comment by russdanner** [comment] 2017-01-11 21:52
Nothing should be bypassed per se ... it's the same API as every other write ... but correct, no clipboard is involved.

**Comment by russdanner** [comment] 2017-01-11 22:19
Assigning this back to me.  We'll use the copy service via the UI for this release. 

I will put a ticket in for C3 to update the business rules for copy

**Comment by russdanner** [comment] 2017-01-12 02:01
Common API line 2018 & 2039
Write is sending false for duplicate

**Comment by uber-rivet** [comment] 2017-01-13 22:11
Actually I've been doing some test and I always got operation property null (meaning not present) the called from studio pipeline process.

**Comment by russdanner** [comment] 2017-01-16 15:09
@dejan-brkic 
I see the UI sends a false where it should send TRUE in the UI but do you see Uber's comment?  
I spoke with Hyanghee and they do rely on that Op code for a use case for a client project. 

Assigned for comment/fix if we are not sending it.

**Comment by dejan-brkic** [comment] 2017-01-16 15:51
There is some misunderstanding or improper use of content lifecycle operations. If property is not set properly than none of operations would work at all, because controller operations is selected based on property value. Issue states that only duplicate operation is not executed. We verified that and found reason why.
I don't know how Uber's test look like and how it is executed. Default implementation of controller is basically a test, it only logs operations (based on property value) and site and path for which it is called works. If proper logging level is turned for groovy script it will start logging operations properly (except for duplicate which is reported as issue).

**Comment by jdrossl** [comment] 2017-01-17 15:54
Testing with the latest 2.5.3 snapshot the issue is not fixed yet.

**Closed** 2017-01-25 23:11 UTC
Labels: blocker, bug
