### ISSUE TITLE
[studio-ui] node selector opens multiple forms on edit

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3337] opened 2019-08-02 00:58 UTC
## Describe the bug
The node/item selector opens a child form when you select an item and then click edit.  It's currently opening the form multiple times (one time for every item in the selector as if the event is triggering too many times)

https://www.loom.com/share/e831f789f4be43679c291ca94f5f1170

## To Reproduce
1. the side bar in an editorial blueprint based site
2. edit the home page
3. go to the features node selector and click on one of the items then click edit
4. note multiple forms open

## Expected behavior
Clicking edit should open one for, for the item the user selected.

## Screenshots
N/A

## Logs
N/A

### Version
Studio Version Number: 3.1.1-SNAPSHOT-2cafd8
Build Number: 2cafd837239dd8ea7a346ed0d83929277e4153df
Build Date/Time: 07-31-2019 14:10:20 -0400

### OS
Any

### Browser
Any

**Comment by jvega190** [comment] 2019-08-05 16:56
@russdanner I'm not being able to reproduce it, using this version:

Studio Version Number: 3.1.1-SNAPSHOT-2613ef
Build Number: 2613efd83d9d67e9d56c3e0ceaa458dabd20bf65
Build Date/Time: 08-05-2019 09:01:39 -0600

https://www.loom.com/share/6238fa9dca9a49349f9d43abac05679b

is there any other detail that I may be missing?

**Comment by sumerjabri** [comment] 2019-08-12 21:34
Duplicate of https://github.com/craftercms/craftercms/issues/3360

Keeping https://github.com/craftercms/craftercms/issues/3360 since it's more detailed.

**Closed** 2019-08-12 21:35 UTC
Labels: bug, duplicate, priority: high
