### ISSUE TITLE
Bitbucket integration does not work

### ISSUE THREAD

**Issue by noblecraft** [craftercms/craftercms#2380] opened 2018-08-26 14:54 UTC
Most likely same as: https://github.com/craftercms/craftercms/issues/2369#issue-353061080

### Expected behavior
Creating new site and link with git (bitbucket) (see: https://blog.craftercms.org/2018/08/21/integrating-crafter-cms-with-bitbucket-for-better-devops/) does not work. 
### Actual behavior
Fails with stacktrace, see below
I have verified git repo url works using command line git

### Steps to reproduce the problem
* Use above blog as reference.
I have tried using basic auth (username/password), 'Remote Git Repository Private Key', and both https and ssh urls combinations. Nothing seems to work.

### Log/stack trace (use https://gist.github.com)
[ERROR] 2018-08-27 00:42:29,290 [http-nio-8080-exec-8] [git.GitContentRepository] | Remote repository not found: origin (https://empirezhu@bitbucket.org/empirezhu/gz_panxi.git)
org.eclipse.jgit.api.errors.TransportException: Duplicate remote ref update is illegal. Affected remote name: refs/heads/master
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:180)
	at org.craftercms.studio.impl.v1.repository.git.GitContentRepository.createSitePushToRemote(GitContentRepository.java:1848)
	at org.craftercms.studio.impl.v1.service.site.SiteServiceImpl.createSitePushToRemote(SiteServiceImpl.java:977)
	at org.craftercms.studio.impl.v1.service.site.SiteServiceImpl.createSiteWithRemoteOption(SiteServiceImpl.java:695)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy66.createSiteWithRemoteOption(Unknown Source)
	at org.craftercms.studio.api.v1.service.site.SiteService$createSiteWithRemoteOption$3.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at scripts.api.impl.site.SpringSiteServices.createSiteWithRemoteOption(SpringSiteServices.groovy:75)
	at scripts.api.impl.site.SpringSiteServices$createSiteWithRemoteOption$3.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at scripts.api.SiteServices.createSiteWithRemoteOption(SiteServices.groovy:74)
	at scripts.api.SiteServices$createSiteWithRemoteOption$4.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at create_post.run(create.post.groovy:214)
	at groovy.util.GroovyScriptEngine.run(GroovyScriptEngine.java:605)
	at org.craftercms.engine.scripting.impl.GroovyScript.execute(GroovyScript.java:55)
	at org.craftercms.engine.controller.rest.RestScriptsController.executeScript(RestScriptsController.java:165)
	at org.craftercms.engine.controller.rest.RestScriptsController.handleRequestInternal(RestScriptsController.java:99)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:174)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)

...

Caused by: org.eclipse.jgit.errors.TransportException: Duplicate remote ref update is illegal. Affected remote name: refs/heads/master
	at org.eclipse.jgit.transport.PushProcess.<init>(PushProcess.java:132)
	at org.eclipse.jgit.transport.Transport.push(Transport.java:1343)
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:169)
	... 111 more
[ERROR] 2018-08-27 00:42:29,295 [http-nio-8080-exec-8] [site.SiteServiceImpl] | Error while creating site: test8 ID: test8 from blueprint: website_editorial. Rolling back.
org.craftercms.studio.api.v1.exception.repository.RemoteRepositoryNotFoundException: Remote repository not found: origin (https://empirezhu@bitbucket.org/empirezhu/gz_panxi.git)
	at org.craftercms.studio.impl.v1.repository.git.GitContentRepository.createSitePushToRemote(GitContentRepository.java:1878)
	at org.craftercms.studio.impl.v1.service.site.SiteServiceImpl.createSitePushToRemote(SiteServiceImpl.java:977)
	at org.craftercms.studio.impl.v1.service.site.SiteServiceImpl.createSiteWithRemoteOption(SiteServiceImpl.java:695)
#### Version
git clone https://github.com/craftercms/craftercms.git
./gradlew init build deploy bundle
So should be master

**Comment by sumerjabri** [comment] 2018-08-27 13:32
Duplicate of https://github.com/craftercms/craftercms/issues/2369

**Comment by noblecraft** [comment] 2018-08-27 14:18
@sumerjabri thanks for looking into this. Do we have an ETA on a fix? What is the crafter project's release cycle? Thanks

**Comment by sumerjabri** [comment] 2018-08-27 14:59
@noblecraft patch releases (like 3.0.17) are normally released every month, we expect 3.0.17 to be released in September (probably mid-September) -- it'll go into `master`. Once the fix is in, you can build from `develop` or cherry-pick the commit if you want it sooner.

**Comment by sumerjabri** [comment] 2018-08-27 15:17
@luishernandezmonge please add this issue to test automation

**Comment by luishernandezmonge** [comment] 2018-09-03 16:16
already added to automation suite.

**Comment by russdanner** [comment] 2018-09-06 03:11
Confirmed

**Closed by russdanner** 2018-09-06 03:11 UTC
Labels: bug, duplicate, priority: high
