### ISSUE TITLE
Unable to create site: Internal server error

### ISSUE THREAD

**Issue by iamRamkumar** [craftercms/craftercms#3141] opened 2019-05-13 12:01 UTC
## Describe the bug
{{ Unable to create site: Please Contact system administration }}

## To Reproduce
1. Created a bare repo
2. Click on 'Create a Site'
3. Chosen a existing blueprint and follow instructions https://docs.craftercms.org/en/3.0/getting-started/your-first-website.html and then clicked create

## Expected behavior
{{ Expected Site will be created but got error notifications message `Unable to create site: Please Contact system administration` }}

## Screenshots
![Screenshot_2](https://user-images.githubusercontent.com/25427547/57753428-bfee7e80-7709-11e9-8091-b98c8662e594.png)

## Logs
[Log Gist](https://gist.github.com/iamRamkumar/e46150db9cd5345573d042cb6f90b9b4)

### Version
{{ Version 3.1.0 }}

### OS
{{ Windows 10 - 64Bit }}

### Browser
{{ Google Chrome 74.0.3729.131 (Official Build) (64-bit) }}

**Comment by yacdaniel** [comment] 2019-05-13 17:45
Hi @iamRamkumar could you provide more details, please? Steps to reproduce, attach the `catalina.out ` file under  `crafter-authoring/logs/tomcat/`,  what version of craftercms are you using, browser/OS, etc. 
I did a install of crafter in a fresh virtual machine and the site was created without problems.
Thanks!

**Comment by iamRamkumar** [comment] 2019-05-15 06:58
## Describe the bug
> Unable to create site: Please Contact system administration

## To Reproduce
Steps to reproduce the behavior:
1. Created a bare repo
2. Click on 'Create a Site'
3. Chosen a existing blueprint and follow instructions https://docs.craftercms.org/en/3.0/getting-started/your-first-website.html and then clicked create
4. See error

## Expected behavior
>Expected Site will be created but got error notifications message `Unable to create site: Please Contact system administration`

## Screenshots
![Screenshot_2](https://user-images.githubusercontent.com/25427547/57753428-bfee7e80-7709-11e9-8091-b98c8662e594.png)


## Logs
[Log Gist](https://gist.github.com/iamRamkumar/e46150db9cd5345573d042cb6f90b9b4)

## Specs
### Version
`Version 3.1.0 `

### OS
`Windows 10 - 64Bit `

### Browser
`Google Chrome 74.0.3729.131 (Official Build) (64-bit)`

**Comment by sumerjabri** [comment] 2019-05-15 14:00
Hi Ram Kumar,

Please go to Google Groups and create a topic there for us to help you. This is not a bug in the project, it's a problem with your setup where Elasticsearch is not coming up.

Google Groups: https://groups.google.com/forum/#!forum/craftercms

We'll be closing this issue.

**Closed by sumerjabri** 2019-05-15 14:00 UTC
