### ISSUE TITLE
[studio-ui] Create "Choose option" or empty option in dropdown control.

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#2193] opened 2018-06-06 15:57 UTC
### Expected behavior
Users should see  "Choose option" or empty option at the first time they open the form.

### Actual behavior
At the first time, the dropdown displays a value, and the validation show a check mark as it is ok, but the user has not selected the option.

### Steps to reproduce the problem
* Create a Site using editorial BP
* Got to Preview page
* On sidebar, create new content under homepage
* Select Category Landing Page
* Se the behavior of category control under articles section

#### Version
Studio Version Number: 3.0.14-SNAPSHOT-972920
Build Number: 97292027f40dc5063a5bba0566cfa8854e84c9bc
Build Date/Time: 06-04-2018 11:20:05 -0600

#### OS
OS X

#### Browser
Chrome browser

**Comment by sumerjabri** [comment] 2018-06-06 19:47
Dupe of #2194

**Closed by sumerjabri** 2018-06-06 19:47 UTC
Labels: duplicate
