### ISSUE TITLE
[studio] Delete service fails on a specific case

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#5402] opened 2022-03-24 22:59 UTC
#### Crafter CMS Version
4.0.0-SNAPSHOT-1c9d28

#### Date of Build
{{If you built Crafter CMS from source, when did you pull the source?}}

#### Describe the bug
`/studio/api/2/content/delete` fails on a specific case, when creating a copy of a page, and copy another into the first copy, then trying to delete the first copy.

#### To Reproduce
1. Go to editorial based site
2. On pages, copy `Health` and paste it under home (haven't tried if duplicating it causes the same).
3. Now copy `Style` and paste it under the new Heath copy (`Health (Copy 1)`)
4. Delete `Health (Copy 1`)
5. See the error

#### Logs
https://gist.github.com/jvega190/c09219f4fcb9b40d7a265f792ceaf143

**Comment by jdrossl** [comment] 2022-03-29 14:23
This was a duplicate of https://github.com/craftercms/craftercms/issues/5412, it's already fixed

**Closed by jdrossl** 2022-03-29 14:23 UTC
Labels: bug, priority: medium, triage
