### ISSUE TITLE
The underscore `_` character does not show up in the code editor

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#7401] opened 2024-10-17 03:00 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x

### Describe the issue

the `_` character does not show up in the code editor

### Steps to reproduce

Steps:

1. Open the code editor
2. Type `_`

### Screenshots and/or videos

See line `String openAIKey = System.getenv("crafter_openai_key")`

![image](https://github.com/user-attachments/assets/f8d91a16-97f7-4703-888d-5acdabcdf4c4)

**Comment by rart** [comment] 2024-10-17 11:19
@russdanner can't reproduce. All the font families used show the underscore just fine on Mac and Windows. We should check on other Linux machines and consider targeting a different monospaced font for Linux. 

The only thing I can think of tweaking is the `font-variant-ligatures` but I'd need an environment to test. You should see if you have some ligature setting on your OS too.

**Comment by sumerjabri** [comment] 2024-10-17 14:12
I confirmed the issue with Roy. It seems that on Linux/Chrome with font size `14px` and font `monospace`, the `_` disappears. Manipulating the `line height` works, but it's not the same for every machine and that field seems to be dynamically calculated by ACE. Instead, bumping the font size to `15px` seems to work. We will start with that, test it on all target machine/browser combos, and see if that suffices for this release. Figuring out how ACE works out `line height` can be a future goal.

**Comment by sumerjabri** [comment] 2024-10-17 15:22
Verified fixed on:
* Mac: Chrome, Safari, Firefox
* Windows: Chrome, Edge, Firefox
* Linux: Chrome, Firefox

**Closed as completed by sumerjabri** 2024-10-17 15:22 UTC
Labels: priority: medium, module: studio-ui
