### ISSUE TITLE
[studio] When you upgrade a site to the latest Studio, then create a new site, the new site should have the default groups `site_admin`, `site_author`

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3091] opened 2019-04-19 12:40 UTC
## Describe the bug
When you upgrade a site to the latest Studio, then create a new site, the role mappings config file has `sitename_admin`, etc for groups in the new site instead of the expected `site_admin` (the default groups for 3.1)

## To Reproduce
1. Create a site in 3.0.20, site `A`
2. Upgrade the site created in 3.0.20 by copying the data folder into a new (3.1) Studio install.  Notice that in the role-mappings config, the groups are now `A_admin`, `A_author`, etc.
3. In the new (3.1) Studio install, create a new site, site `B`
4. Open the role-mappings config, notice the groups for the new site listed is `B_admin`, `B_author`, etc. instead of the expected `site_admin`, `site_author`
, etc

## Expected behavior
When you upgrade a site to 3.1, then create a new site in 3.1, the role-mappings config created for the new site should have the default groups `site_admin`, `site_author`, etc. 

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.0-SNAPSHOT-a9a9be
Build Number: a9a9bed7345e34a4bbcc1b6f4e73f0bf2e69d9a6
Build Date/Time: 04-18-2019 11:30:38 -0400

### OS
OS X

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by sumerjabri** [comment] 2019-04-19 15:11
Duplicate of: https://github.com/craftercms/craftercms/issues/3089

**Closed by sumerjabri** 2019-04-19 15:11 UTC
Labels: duplicate
