### ISSUE TITLE
Delete project fails on dashboard refresh and site is left half-deleted

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#6682] opened 2024-04-15 14:12 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [x] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

In Studio, when a big project is being deleted and you refresh the project dashboard (the one listing all projects), sometimes the deletion fails and the project is left half-deleted and never disappears from the dashboard

CI: 4923

### Steps to reproduce

Steps:

1. Create a huge project that would definitely take time deleting.
2. Start tailing the Studio logs
3. Delete the project
4. Immediately start refreshing the dashboard were all project appear every second (since the issue seems to be a race condition)
   1. If you can't do this constant refresh, you can also run `jstack` every once in a while. When you see a stack trace that indicates the site being deleted from the DB, immediately start refreshing the dashboard quickly

You should see in the Studio logs that the API call to delete the project failed with similar stack traces to the ones attached. If you check the dashboard you should also notice that the project is basically "stuck" in a deleted state, and from then on it never disappears.

### Relevant log output

```shell
Example #1: https://gist.github.com/avasquez614/2b015375ab24a7dbc9152c2ed89e46c9
Example #2: https://gist.github.com/avasquez614/6cff6d627e82d46e609bbe83a567196c
```

**Comment by jmendeza** [comment] 2024-04-16 19:53
This issue is caused by a very specific race condition. It happens if after deleting the site repository, the configuration cache still contains the role configs but not the permission config.
The fix avoids permissions check during site delete cache invalidation, since it is a system operation.

**Comment by Euquimides** [comment] 2024-06-10 18:31
Hi! Updated and rechecked this issue. Fix verified. Thank you! Closing this ticket.

**Closed by Euquimides** 2024-06-10 18:31 UTC
Labels: bug, priority: high, CI, module: studio
