### ISSUE TITLE
[craftercms] Add Profile/Social Admin Consoles to Delivery

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#896] opened 2017-05-31 15:19 UTC
Please add the Crafter Profile/Social admin consoles to the delivery bundle and wire accordingly.

**Comment by cortiz** [comment] 2017-06-06 23:00
Solve in #939

**Comment by sumerjabri** [comment] 2017-06-07 14:06
Doesn't seem to work.

Steps I Used
-------------
- `./gradlew -Pcrafter.profile=true -Penv=delivery build deploy`
- `ls crafter-delivery-env/bin/apache-tomcat/webapps`

Result
```
~/code/crafter/craftercms (master ✔) ᐅ ls crafter-delivery-env/bin/apache-tomcat/webapps
ROOT.war            crafter-profile.war crafter-search.war  crafter-social.war
```

**Comment by cortiz** [comment] 2017-06-23 16:10
I'm moving this back to test & validate, I'm unable to reproduce it on Linux/windows/macOS but it's possible could be related to the issue that artifacts sometimes are not copied #958

**Comment by cortiz** [comment] 2017-06-23 17:32
Solve in #1022

**Closed** 2017-07-10 21:25 UTC
Labels: enhancement, Priority: High
