### ISSUE TITLE
[studio-ui] Main menu right panel items disappears

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2478] opened 2018-09-14 18:44 UTC
### Expected behavior
Main menu right panel items should not disappear

### Actual behavior
Main menu right panel items disappears

<img width="645" alt="screen shot 2018-09-14 at 2 27 05 pm" src="https://user-images.githubusercontent.com/25483966/45568481-c51dc580-b82a-11e8-9df7-167035d1330e.png">

### Steps to reproduce the problem
* Login to Studio.  You'll see the global menu screen after logging in, and on the right side, you'll see the `Sites` list
* On the top right of you Studio, click on the Main Menu icon, notice the right panel items disappear
* Right click on your browser and inspect, notice there are some error messages there

### Log/stack trace (use https://gist.github.com)
Here's a short clip:
https://www.useloom.com/share/c70fed012759409e84d8490889f4597f

Error when you inspect:
```
Error: Syntax error, unrecognized expression: #:hover
    at Function.Sizzle.error (jquery.js?version=936cbfa97c165f2eed2f40f2cfe6d00403e99063:1458)
    at Sizzle.tokenize (jquery.js?version=936cbfa97c165f2eed2f40f2cfe6d00403e99063:2075)
    at Sizzle.select (jquery.js?version=936cbfa97c165f2eed2f40f2cfe6d00403e99063:2479)
    at Function.Sizzle [as find] (jquery.js?version=936cbfa97c165f2eed2f40f2cfe6d00403e99063:855)
    at jQuery.fn.init.find (jquery.js?version=936cbfa97c165f2eed2f40f2cfe6d00403e99063:2695)
    at new jQuery.fn.init (jquery.js?version=936cbfa97c165f2eed2f40f2cfe6d00403e99063:2803)
    at jQuery (jquery.js?version=936cbfa97c165f2eed2f40f2cfe6d00403e99063:76)
    at main.js?version=936cbfa97c165f2eed2f40f2cfe6d00403e99063:639
    at angular.js?version=936cbfa97c165f2eed2f40f2cfe6d00403e99063:18744
    at completeOutstandingRequest (angular.js?version=936cbfa97c165f2eed2f40f2cfe6d00403e99063:5804)
```

<img width="312" alt="screen shot 2018-09-14 at 2 35 37 pm" src="https://user-images.githubusercontent.com/25483966/45568767-79b7e700-b82b-11e8-9358-ed7eaeb69c33.png">

#### Version
```
Studio Version Number: 3.1.0-SNAPSHOT-de85a7
Build Number: de85a78fecfadc32b817c6fd2855ae848b390827
Build Date/Time: 09-14-2018 11:55:35 -0400
```
#### OS
OS X
#### Browser
Chrome browser

**Comment by sumerjabri** [comment] 2018-09-14 18:50
Duplicate of https://github.com/craftercms/craftercms/issues/2469

**Closed by sumerjabri** 2018-09-14 18:50 UTC
