### ISSUE TITLE
[studio-ui] Studio configuration UI strips trailing whitespaces in RTE 5 configuration file

### ISSUE THREAD

**Issue by tfield** [craftercms/craftercms#4629] opened 2021-04-08 02:32 UTC
## Describe the bug
When editing RTE config files in the Studio UI, trailing whitespaces are deleted when the file is saved. This breaks the "plugin" and "toolbarItem" sections, as they rely on the space character as the delimiter between items.

## To Reproduce
1. Go to RTE 5 config screen in the Studio Site Admin UI
2. Add a toolbar item on a new line, but add a trailing space on the previous line
3. Save the config file
4. Note that the UI has removed the trailing space
5. Try to use the RTE in a content form
6. Observe the configuration error message

## Expected behavior
No error

## Screenshots
See https://craftersoftware.zendesk.com/hc/en-us/requests/2144

## Logs
n/a

### Version
3.1.10

### OS
macOS

### Browser
chrome

## Additional context
n/a

**Comment by rart** [comment] 2021-04-09 14:04
Cannot reproduce. Perhaps fixed in more recent versions?

In any case, the UI doesn't trim or otherwise massage the contents of the XML documents on the editor. This would be a situation in the backend XML deserializer. For context, the RTE calls `api/1/get-configuration` service which returns the contents of the XML as JSON.

Testing leaving a space at the end of the line and saving, I can both 
1. see the space on the config file if I reload the config editor and load that file again 
2. see the JSON showing the space between the last item of the "previous line" and the next item on the next line

**Closed** 2021-04-13 00:35 UTC
Labels: CI, bug, can't reproduce, priority: medium
