### ISSUE TITLE
Logging Level tools should allow you to set levels Engine as well

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2989] opened 2019-03-22 15:01 UTC
**Is your feature request related to a problem? Please describe.**
The logging level tool on the Site Config panel of Crafter Studio should make it easy to set logging levels of Crafter Engine (in addition to studio.)

**Describe the solution you'd like**
Add a tabs for Crafter Studio and Crafter Engine.  This gives an approach where we can add other services later as their configuration is pulled in to and deployed from Studio.

**Comment by sumerjabri** [comment] 2023-09-06 18:37
Related to https://github.com/craftercms/craftercms/issues/2086

**Comment by sumerjabri** [comment] 2024-03-27 21:54
This seems to be a dupe of the ticket mentioned above. Re-eval.

**Closed** 2024-08-08 14:47 UTC
Labels: new feature, priority: low, CI, triage, module: engine, reevaluate
