### ISSUE TITLE
[Docker] Docker images don't work due > The usage of relative paths for mountpoints will now produce a warning (librunc)

### ISSUE THREAD

**Issue by cortiz** [craftercms/craftercms#4799] opened 2021-06-22 20:09 UTC
## Describe the bug

Due to https://github.com/opencontainers/runc/pull/2917 and  https://github.com/opencontainers/runc/pull/3004 docker/runc 
in some Docker environments creating or running a Crafter image fails, this issue was fixed on runc 1.0.0 that was released today, but until that is rollout with the OS package management tools the issue will persist (Redhat 8, Ubuntu 20.04LTS) 
Also on the Release notes of runc 

> Deprecations:
>     The usage of relative paths for mountpoints will now produce a warning
>     (such configurations are outside of the spec, and in future runc will
>     produce an error when given such configurations). (#2917, #3004)

Adding full mount points will also future-proof the current docker images.

Regards

**Comment by avasquez614** [comment] 2021-06-25 15:06
@cortiz is this issue the same as this one? https://github.com/craftercms/craftercms/issues/4759.

**Comment by cortiz** [comment] 2021-06-25 16:54
@avasquez614 Yes

**Comment by sumerjabri** [comment] 2021-07-06 15:56
Fixed in 3.1.15

**Comment by phuongnq** [comment] 2021-07-28 08:04
@cortiz The issue is fixed in 3.1.15. Does the fix work for you?

**Comment by russdanner** [comment] 2021-12-01 01:09
@phuongnq please confirm in 4.x and close

**Comment by phuongnq** [comment] 2021-12-03 10:55
Confirmed with version 

```
Docker version 20.10.11, build dea9396
```

Run the following command is fine:

```
docker-compose down && docker-compose up
```

**Closed by phuongnq** 2021-12-03 10:55 UTC
Labels: priority: medium, quality, help wanted
