### ISSUE TITLE
[studio] Create User API, appears the status incorrect when the user use the invalid parameters.

### ISSUE THREAD

**Issue by gortizcrafter** [craftercms/craftercms#650] opened 2017-03-29 17:54 UTC
Steps:

1.Execute the json to create a user with INVALID PARAMETERS.
http://docs.craftercms.org/en/latest/developers/projects/studio/api/user-management/create-user.html

*Current Behavior

The response always is :
Status: 500
Response Body: https://www.screencast.com/t/pHd0YHCbN1b

*Expected Behavior

The response expected should be:
Status: 
400
Response Body:
{ "message" : "Invalid parameter(s)" }

**Comment by sumerjabri** [comment] 2017-03-29 17:59
Duplicate of #635 

Please don't look for 400 errors because all APIs need to be updated. We will use #635 to track that.

**Closed by sumerjabri** 2017-03-29 17:59 UTC
Labels: duplicate
