### ISSUE TITLE
[studio-ui] Add the ability to re-enable a user's account via the UI

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#4802] opened 2021-06-24 14:52 UTC
# Feature Request

#### Is your feature request related to a problem? Please describe.
When a user is 'deleted' from Studio, their account is disabled but not deleted from the DB. This leads to an issue when wanting to add a user back to Studio, the user cannot be created because it already exists in the DB. The current workaround is to manually re-enable the user in the DB. 

#### Describe the solution you'd like
The UI should allow functionality for the re-enabling of a user that has been 'deleted'.

#### Describe alternatives you've considered
Manually re-enabling the user in the DB.

#### Additional context
N/A

**Comment by russdanner** [comment] 2021-06-24 16:25
I believe this is a duplicate of this ticket:
https://github.com/craftercms/craftercms/issues/4043

**Closed** 2021-06-24 16:27 UTC
Labels: duplicate
