### ISSUE TITLE
[studio-ui] support file size limits on data sources, image and video pickers

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3106] opened 2019-04-25 14:37 UTC
Related to: #3107 
**Is your feature request related to a problem? Please describe.**
Admins want to constrain the sizes of images, documents and other files that are added to the system.

**Describe the solution you'd like**
Support a UI enforced file size limit via datasources and common asset picker form controls (image and video.)

Content type admins will chose if it's more efficient/effective to set limits at the control level or the data source.  

UI level enforcement provides quick feedback to users and eliminates any network activity etc.  

**Describe alternatives you've considered**
Configuring limits at the UI level currently would need to be done at several places:
- The sidebar for upload/bulk upload
- Browse dialogs
- Form controls and data sources
- APIS

It may be better to provide some central configuration in the studio site-config that just defines the size limits per path / mimetype or role and then have all of these components consume it.

**Comment by sumerjabri** [comment] 2020-09-22 15:52
Will close in favor of a new Site Policy ticket.

**Comment by sumerjabri** [comment] 2020-10-15 17:10
Duplicate of https://github.com/craftercms/craftercms/issues/4354

**Closed by sumerjabri** 2020-10-15 17:10 UTC
Labels: CI, enhancement, priority: medium, triage
