### ISSUE TITLE
[studio-ui] support file size limits on bulk upload

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3107] opened 2019-04-25 14:50 UTC
Related to: #3106 
**Is your feature request related to a problem? Please describe.**
Admins want to limit the sizes of files uploaded to the CMS

**Describe the solution you'd like**
Support the ability for developers to specify size limits for paths via params section of the `wcm-assets-folder` sidebar module. Enforce these limits via the UI on upload and bulk upload operations.

```
  <!-- Static Assets -->
  <modulehook>
      <name>wcm-assets-folder</name>                                    
      <params>
          <label>Static Assets</label>
          <path>/static-assets</path>
          <showRootItem>true</showRootItem>
          <onClick>none</onClick>
          <constraints>
              <constraint>
                  <type>size</type>
                  <!-- a regex that matches a path -->
                 <path>^/static-assets/images/hero/.*</path>
                 <!-- a size in bytes -->
                 <value>1000000</value>
          </constraint>
         <constraints>
      </params>
  </modulehook>
```

**Describe alternatives you've considered**
APIs should also be able to limit sizes on the back end.

Configuring limits at the UI level currently would need to be done at several places:
- The sidebar for upload/bulk upload
- Browse dialogs
- Form controls and data sources
- APIS

It may be better to provide some central configuration in the studio site-config that just defines the size limits per path / mimetype or role and then have all of these components consume it.

**Comment by sumerjabri** [comment] 2020-09-22 15:51
Will close in favor of a new Site Policy ticket.

**Comment by sumerjabri** [comment] 2020-10-15 17:09
Duplicate of Site Policies: https://github.com/craftercms/craftercms/issues/4354

**Closed by sumerjabri** 2020-10-15 17:09 UTC
Labels: CI, enhancement, priority: medium, triage
