### ISSUE TITLE
[studio-ui] "static-assets", "templates" and "scripts" folders are all marked as edited in the Sidebar on site creation

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#4493] opened 2021-01-27 17:16 UTC
## Describe the bug

"static-assets", "templates" and "scripts" folders are all marked as edited in the Sidebar on site creation

## To Reproduce
1. Go to `Sites`, then click on the `Create Site` button
2. Select any bp.  For our example, we'll use the empty bp
3. Open the Sidebar and navigate to either `static-assets`, `templates` or `scripts`.  Notice that all the folders there are marked as edited
<img width="266" alt="Screen Shot 2021-01-27 at 12 10 56 PM" src="https://user-images.githubusercontent.com/25483966/106027272-bbfabf80-6098-11eb-9d14-5ff16db07370.png">

## Expected behavior
The folders shouldn't have a workflow status. (I think folder states are not tracked)

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 4.0.0-SNAPSHOT-d99795
Build Number: d99795680a9de37c090bb2a9bff9caf341b09d20
Build Date/Time: 01-22-2021 10:03:29 -0500

### OS
macOS 10.15.7

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment] 2021-03-19 14:51
This is UI issue. State bitmap in the DB for all items is  1 (NEW)

**Comment by rart** [comment] 2021-03-19 15:02
The old/legacy sidebar tree is not driven by the state bitmap but rather with the old api flags.

Will check the UI and comment back & reassign or fix. @jvega190

**Comment by jvega190** [comment] 2021-03-19 17:43
There's an issue in the UI, fixing

**Comment by rart** [comment] 2021-03-19 18:58
@sumerjabri 

- The old/legacy sidebar tree is not driven by the state bitmap but rather with the old api flags. The issue is that the backend sends the `inProgress` flag set as true. This causes the UI to set the edited icon. To address, we're adding logic to give precedence to the `new` flag — which the API also sends as true in these cases.

- We didn't use to show status icons on folders before 4 (see #1653). According to #1653, the current behaviour is actually correct, as #1653 literally states "renamed/new folder should display an edited (pencil) icon" (i.e.g this present ticket collides with the #1653).

- We still don't display icons for folders on the pages and components widgets. Is there a reason to break consistency of how folders get displayed between `pages/components` and `assets/templates/scripts`?
  - FYI: [Slack thread](https://craftersoftware.slack.com/archives/C0EMZALLV/p1607358393415100)

Do we:
1. Leave the current fix in and be done
2. Revert displaying icons on folders for assets/templates/scripts
3. Show icons on pages/components too

**Comment by jvega190** [comment] 2021-03-20 01:40
Draft PR created, waiting for the decision to see if changes are needed

**Comment by rart** [comment] 2021-03-22 14:33
Per discussion with sumer we're rolling back #1653 which in turns fixes this.

@jvega190 ping me for details; want to see if some of these edits are still good to merge.

**Closed** 2021-03-22 21:33 UTC
Labels: bug, priority: medium, triage
