### ISSUE TITLE
[studio-ui] All content pages under Pages are displayed as Edited (icon) when user goes to preview as second time (create site, go back to sites and go to preview)

### ISSUE THREAD

**Issue by luishernandezmonge** [craftercms/craftercms#2541] opened 2018-10-04 22:11 UTC
### Expected behavior
All the contents should not be displayed as edited if user does not edit them.

### Actual behavior
All contents are displayed as edited after click on preview link.

Watch the next video:
https://www.useloom.com/share/080c98c7b3ec45f68e57fa7a918c8e16

### Steps to reproduce the problem
* Go to studio and login as admin
* Create a new site using: Empty bp or WebSite Editorial bp
* Go back to sites (clicking on Global menu contextual navigation option)
* Click on the Preview link for the site created and review all contents under Pages.

### Log/stack trace (use https://gist.github.com)
https://gist.github.com/luishernandezmonge/f2176d81af6a91dc7347c15504d63816

#### Version
Studio Version Number: 3.1.0-SNAPSHOT-216805
Build Number: 2168056eaab5fb4ab35dc9f212a0a805e03da2c3
Build Date/Time: 10-04-2018 15:57:31 -0600
#### OS
Mac OSX
#### Browser
Chrome

**Comment by dejan-brkic** [comment] 2018-10-05 15:35
@sumerjabri @avasquez614 @jdrossl 
The issue is caused by the Upgrade Manager. Even with a clean environment and with the latest build, an upgrade is performed and all files are marked as edited (repo sync picks up the commit from upgrade manager and processes them as a manual edit).

**Comment by jdrossl** [comment] 2018-10-05 16:00
@dejan-brkic why would this happen?
- the upgrade is done before inserting data in the db so why would it matter how many commits there are?
- why one commit affects all files if it only contains changes for one?

**Comment by dejan-brkic** [comment] 2018-10-05 19:09
Done
PR:
https://github.com/craftercms/studio/pull/1312

**Comment by alhambrav** [comment] 2018-10-08 17:56
Verified fixed.

**Closed by alhambrav** 2018-10-08 17:56 UTC
Labels: bug, priority: high
