### ISSUE TITLE
[studio-ui] Node Selector with Multiple Child Content Sources Launches Many Windows

### ISSUE THREAD

**Issue by AParise1217** [craftercms/craftercms#3360] opened 2019-08-12 14:25 UTC
## Describe the bug
When a Node Selector field has many Child Content Sources selected, many editor windows are launched when using this field in the Studio UI for content of this type.

## To Reproduce

1. Start with the Editorial Blueprint.

2. On the "Component - Left Rail" Content Type, create a new "Child Content" Data Source.

For Example:
![Screen Shot 2019-08-12 at 10 29 50 AM](https://user-images.githubusercontent.com/23058249/62872794-35a7bd80-bcec-11e9-8992-949f3d68c5af.png)
![Screen Shot 2019-08-12 at 10 29 56 AM](https://user-images.githubusercontent.com/23058249/62872802-38a2ae00-bcec-11e9-94bf-b3c9eb9d716c.png)

3. Update the "Widgets" Node Selector field to use this new Child Content Data Source, as well.

For Example: 
![Screen Shot 2019-08-12 at 10 31 37 AM](https://user-images.githubusercontent.com/23058249/62872889-638d0200-bcec-11e9-9430-054860d560e4.png)

4. Save and close the component definition.

5. Edit the "Home" Page in the Studio UI.
![Screen Shot 2019-08-12 at 10 33 35 AM](https://user-images.githubusercontent.com/23058249/62873052-ad75e800-bcec-11e9-9f46-3daaa4c5002f.png)

6. Edit the "Left Rail with Latest Articles" Child Content.
![Screen Shot 2019-08-12 at 10 34 15 AM](https://user-images.githubusercontent.com/23058249/62873113-cd0d1080-bcec-11e9-9b0b-7475018c9fae.png)

7. Select any of the "Widgets" Child Content, and hit "Edit"
![Screen Shot 2019-08-12 at 10 35 01 AM](https://user-images.githubusercontent.com/23058249/62873156-e3b36780-bcec-11e9-970d-bebd600313b4.png)

8. Observe the Multiple Modals that are Launched

![Multiple-Editor-Windows-Bug](https://user-images.githubusercontent.com/23058249/62873378-4b69b280-bced-11e9-9b3e-d9b4c5a59af2.gif)

## Expected behavior
Since there is only one component selected for editing, I expect only one editor window to be launched. If a Node Selector should only have one Child Content data source, then there should not be the option for many to be selected in the definition editor.

## Screenshots
See above repro for the screenshots walking through the sequence.

### Version
Locally:
Studio Version Number: 3.0.16-a037f1
Build Number: a037f1f2c41adc5f5e76766d2609a4ded125d492
Build Date/Time: 02-04-2019 09:43:37 -0500

I can also repro this on our production box which is running:
Studio Version Number: 3.0.18E-1179a7
Build Number: 1179a7d00cd9b7ae81cdfa876c30b807bf995fce
Build Date/Time: 10-26-2018 16:32:54 -0400

### OS
MacOs Mojave v10.14.3 (18D109)

### Browser
Chrome Version 76.0.3809.100 (Official Build) (64-bit) (Latest as of 12 August 2019)

**Comment by sumerjabri** [comment] 2019-08-12 21:35
@jvega190 this is a duplicate of https://github.com/craftercms/craftercms/issues/3337 but more detailed. We'll keep this one.

**Comment by russdanner** [comment] 2019-08-19 14:30
https://www.loom.com/share/a1a32129ca614e869bb333fdce69eb09
The behavior I am seeing at the moment is that edit has _NO_ effect.
The user should be able to select an item by clicking on it and then clicking edit

**Comment by yacdaniel** [comment] 2019-08-21 20:52
Verified fixed in ` 3.0.26-SNAPSHOT` and `3.1.1-SNAPSHOT`.

**Closed by yacdaniel** 2019-08-21 20:52 UTC
Labels: CI, bug, priority: high
