### ISSUE TITLE
[studio] Cut/paste/rename fails

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1162] opened 2017-07-26 15:23 UTC
Per our conversation:
https://gist.github.com/sumerjabri/a8d8a1f909861d270c171ba1acfcbc0e
https://gist.github.com/sumerjabri/dcda111e537afdb9d68058035a7b372e

**Comment by dejan-brkic** [comment] 2017-07-26 17:10
Done
PR:
https://github.com/craftercms/studio/pull/810

**Comment by sumerjabri** [comment] 2017-07-26 18:02
https://gist.github.com/sumerjabri/f6e9b9b973d1523e70068ae292529ed6

**Comment by dejan-brkic** [comment] 2017-07-26 20:41
Done
PR:
https://github.com/craftercms/studio/pull/812

**Comment by sumerjabri** [comment] 2017-07-26 21:40
This happened during bulk publish: https://gist.github.com/sumerjabri/887a619cf3bed7b20f71bd748b152248

**Comment by sumerjabri** [comment] 2017-07-26 21:56
Steps to Reproduce
============
* copy a page to my folder
* rename it
* rename it back
* publish it
* rename it again
* publish it

Makes git sad:
```
[ERROR] 2017-07-26 17:47:27,989 [studioSchedulerFactoryBean_Worker-7] [git.GitContentRepository] | Conflict executing cherry-pick with default merge strategy. 
[ERROR] 2017-07-26 17:48:07,812 [studioSchedulerFactoryBean_Worker-1] [git.GitContentRepository] | Conflict executing cherry-pick with default merge strategy. 
```
* Then copy big-tree one under page
* bulk publish the new page tree

Full logs:
https://gist.github.com/sumerjabri/9081a5e4cb1185b63d4b5410a964881c

**Comment by dejan-brkic** [comment] 2017-07-27 14:58
Not able to reproduce bulk go live error. Reduced log level since error message is just reporting conflict and after that it is resolved with merge strategy THEIRS (patched jgit class)

PR:
https://github.com/craftercms/studio/pull/815

**Comment by sumerjabri** [comment] 2017-07-27 19:02
New Steps to Reproduce
==================
* Create a site based on Editorial BP
* Copy `Technology` page and paste it under `articles`
* Copy `articles/2017` and paste it under `articles/Technology`
* Publish `Technology`
* Rename `Technology` to `technology-newname` `Technology New Name`
* Publish `Technology New Name`
* Publish `articles/Technology/2017/3/Top Clubs in Virginia`

Breaks with: https://gist.github.com/sumerjabri/f122e260f670a0e6241566bb8ff72e47

**Comment by dejan-brkic** [comment] 2017-07-27 22:00
Done
PR:
https://github.com/craftercms/studio/pull/817

**Comment by sumerjabri** [comment] 2017-07-27 22:37
@dejan-brkic I noticed some logging was removed, please add logs at debug level to help us understand better the execution flow as needed.

**Comment by dejan-brkic** [comment] 2017-07-28 15:19
Done
PR:
https://github.com/craftercms/studio/pull/819

**Comment by russdanner** [comment] 2017-07-28 20:06
Verified

**Closed by russdanner** 2017-07-28 20:06 UTC
Labels: bug, Priority: Highest!
