### ISSUE TITLE
Dashboard API Bugs

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#5428] opened 2022-04-01 18:18 UTC
CI: 4793

- [x] 1. Unpublished API: brings no no results 
  - _JR: can't reproduce, this only includes items that have never been published -> new items_
  - _RA: per discussion, should include new & edited too_
- [x] 2. Unpublished API: rename `unPublishedItems` to `unpublishedItems` in response and OAS
- [x] 3. Scheduled API: brings no results
  - _JR: could not reproduce_
- [x] 3a. Scheduled API: username is null
- [ ] 3b. Scheduled API: add submission comment (Related to #6575)
- [x] 4. Activity API: "approve" and "approved scheduled" are not tracked
  - _JR: both are PUBLISH_
- [x] 5. Activity API: Scheduled an item (with admin). Not showing in the log.
  - _JR: will show up ad PUBLISH_
- [x] 6. Expiring API: dates not working reliably
- [ ] 7. Pending Approval API: package id, username, and schedule (when applicable) are all null.
  - _JR: package id & size will be null until we implement Publishing Packages, fixed username, schedule & total_
- [ ] 8. Pending Approval API: add submission comment to the response 
  - _JR: possible improvment for later?_
- [x] 9. `pending_approval/{id}`: Throws 500 (BadSqlGrammarException)
  - _JR: can't be implemented, we don't have package id yet_
- [x] 10. History API: Throws 500 (TooManyResultsException: Expected one result (or null) to be returned by selectOne(), but found: 2)
- [x] 11. `history/{id}`: Throws 500 (BadSqlGrammarException) 
  - _JR: can't reproduce_
  - _RA: it throws a 500 instead of a 404 when you send an id that doesn't exist_
- [x] 12. `/dashboard/publishing/stats`: OAS is wrong, says response is an array but it's just an object

**Note**: 

- [ ] 13. Acitvity API: Requesting publishing with schedule has no distinction to without schedule 
  - _JR: seems to be by design_
- [x] 14. Expired API: brings dependencies
- [x] 15. Expiring API: brings expired content if dates cover content that's expired (semantics issue: and expired item is not expiring)
  - _JR: possible improvement for later?_

**Comment by jdrossl** [comment] 2022-04-01 23:02
@rart most of the issues should be fixed now, there are a couple that are not possible right now. Please review the comments I added and the fixes. We can discuss further if something is still wrong.

**Comment by rart** [comment] 2022-04-02 08:46
**(1)** @sumerjabri @russdanner feels like unpublished should include **everything** that's not published, including **edited** items but per @jdrossl, it only shows new items (i.e. never published). 
  - If we don't include edited stuff here, there's nowhere for those to be seen. Perhaps it's ok as that's how it is today?
  - If we don't include edited stuff here, then we should rename the widget to "Never Published"

**(3)** @jdrossl I think the confusion was around approval. @sumerjabri @russdanner items won't show on scheduled until approved (i.e. submitted with scheduled don't show, only approved scheduled). Ok?

**(4)** I don't think not tracking approve and approve scheduled is quite right. Approve is less of a problem but with approve schedule, something may not be published until several days in the future and activity log doesn't show anything for the fact that the item(s) have now been approved — in these instances, the last entry is the request for publish. Publish will show up until the item is published. I think this needs to be fixed at least for the scheduled case. Given that publishing can take a few minutes too, perhaps for approve too.

**(5)** Same case as with not tracking approve schedule. If something is scheduled for publish several days from now, there's nothing in activity that shows that action until day of the publishing comes.

**(7)** The pending approval API is functionally **completely** useless as it stand. 

    - There is no package information **nor** item information. This means the UI can't let user select the items/package and approve them. See sample response below.
    - We also can't display the "oldest request" stat as planned on the widget as the API doesn't return this value. See screenshot below. We can remove the stats for now, the biggest issue is the previous bullet.
```json
{
  "label": null,
  "submitter": { "username": "author", "firstName": "Jane", "lastName": "Doe", },
  "size": 0,
  "publishingTarget": "live",
  "schedule": null,
  "id": null
}
```
![image](https://user-images.githubusercontent.com/3928341/161374974-4886a957-cb64-49de-b3b4-82ea0474557f.png)

**(8)** It's important to do this now if we display as packages to provide users with something contextual to read, otherwise it'll mostly look as dummy text. If we display as items, it's of less importance. Seems like an easy addition though, no? As it stands, the API is unusable to render a useful UI (see # 7 above).

- [ ] 16. Unpublished API brings the folders of the pages that show

**Comment by rart** [comment] 2022-04-04 16:39
- [ ] 20. History api: add `submissionComment` & `approvalComment` to response

**Comment by sumerjabri** [comment] 2024-01-18 21:13
If backend work is needed, we may push this to the next patch release.

**Comment by jvega190** [comment] 2024-03-18 20:57
@rart @sumerjabri 
Updates: 
#7: doesn't apply anymore, since the API now return items instead of packages
#8: the API response is a list of sandboxItems, which don't have a comment prop. Is this something that we still want?
#13: Per comment, that's something done by design, do we still want this update?
#20: We have a 'comment' prop in the response. Do we want both `submissionComment` and `approvalComment`?

From this [comments](https://github.com/craftercms/craftercms/issues/5428#issuecomment-1086592770), comment #7, bullet b, the API returns now a list of sandboxItems, which have more info that can be used. Do we want to add back those  stats?

**Closed** 2024-07-12 15:36 UTC
Labels: bug, priority: high, module: studio-ui, module: studio
